ecommerce/Controllers/ProdutoController.cs
using ecommerce.DAO;
using ecommerce.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ecommerce.Controllers
{
    public class ProdutoController : Controller
    {
        private ProdutoDAO produtoDAO;

        public ProdutoController(ProdutoDAO produtoDAO)
        {
            this.produtoDAO = produtoDAO;
        }

        public ActionResult Index()
        {
            var produtos = produtoDAO.Lista();
            return View(produtos);
        }

        public ActionResult Adiciona()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adiciona(Produto produto)
        {
            if (ModelState.IsValid)
            {
                produtoDAO.Adiciona(produto);
                return RedirectToAction("Index");
            }
            else
            {
                return View(produto);
            }
        }

        public ActionResult Edita(int id)
        {
            var produto = produtoDAO.BuscaPorId(id);
            return View(produto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edita(Produto produto)
        {
            if (ModelState.IsValid)
            {
                var Produto = produtoDAO.BuscaPorId(produto.Id);
                Produto.Nome = produto.Nome;
                Produto.Preco = produto.Preco;
                produtoDAO.Edita();
                return RedirectToAction("Index");
            }
            else
            {
                return View(produto);
            }
        }

        public ActionResult Remove(int id)
        {
            var produto = produtoDAO.BuscaPorId(id);
            return View(produto);
        }
     
        public ActionResult ConfirmaRemove(int id)
        {
            var produto = produtoDAO.BuscaPorId(id);
            produtoDAO.Remove(produto);
            return RedirectToAction("Index");
        }
    }
}

ecommerce/Views/Produto/Adiciona.cshtml
@model ecommerce.Entidades.Produto

@{
    ViewBag.Title = "Adiciona";
}

<h2>Adiciona</h2>


@using (Html.BeginForm("Adiciona", "Produto", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(p => p.Nome, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(p => p.Nome, new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(p => p.Preco, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(p => p.Preco, new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para a lista de produtos", "Index")
</div>

ecommerce/Views/Produto/Edita.cshtml
@model ecommerce.Entidades.Produto

@{
    ViewBag.Title = "Edita";
}

<h2>Editar</h2>
@using (Html.BeginForm("Edita", "Produto", FormMethod.Post))
{
     @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Produto</h4>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(p => p.Nome, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(p => p.Nome, new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Nome, "Preencha o campo nome", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(p => p.Preco, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(p => p.Preco, new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Nome, "Preencha o campo preço", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-default" />
            </div>
        </div>
    </div>
     

}
    <div>
        @Html.ActionLink("Voltar para a lista de produtos", "Index")
    </div>

ecommerce/Views/Produto/Index.cshtml
@model IEnumerable<ecommerce.Entidades.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Adicionar produto", "Adiciona")
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edita", new { id=item.Id}) |
            @Html.ActionLink("Remover", "Remove", new { id=item.Id, nome=item.Nome, preco=item.Preco })
        </td>
    </tr>
}

</table>

ecommerce/Views/Produto/Remove.cshtml
@model ecommerce.Entidades.Produto
@{
    ViewBag.Title = "Remove";
}

<h1>Remover Produto</h1>

<h2>Tem certeza que deseja remover esse Produto?</h2>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(p => p.Nome)</th>
            <th>@Html.DisplayNameFor(p => p.Preco)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Html.DisplayFor(p => p.Nome)</td>
            <td>@Html.DisplayFor(p => p.Preco)</td>
        </tr>
    </tbody>
</table>

    @Html.ActionLink("Sim", "ConfirmaRemove", new { id = Model.Id }, new { @class = "btn btn-default" })
    @Html.ActionLink("Não", "Index", new { }, new { @class = "btn btn-default" })

ecommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>